### ISSUE TITLE
Too many song

### ISSUE THREAD

**Issue by jehendeoff** [demaisj/soundcloud-rp#23]
Hello, I would like to report a bug I found with the artwork upload.

If the limit of assets in the discord application is at maximum, it will put nothing in the discord rich presence, I think it would be possible to fix this by putting several applications, even if I think it would be impossible to know when the limit of assets in the application is at maximum. Or another solution would be when a new music is played but there is no more space in the assets, to take the original assets (as if the artwork upload was disabled).

**Comment by demaisj** [comment]
Hello,
I think something is wrong in your instance. I use this program daily, it is hitting the asset limit without any problems since many months now.
Normally, the server will delete some assets if the limit is reached. Maybe you have a configuration problem.
Debugging the code is hard at the moment, so here's the steps:
- edit the file `/src/procedures/activity.js` and add a new line just after [line 115](https://github.com/demaisj/soundcloud-rp/blob/master/src/procedures/activity.js#L115) with this code :
```js
debug('error', err);
```
- then run the server with this command `set DEBUG=soundcloud-rp:* & npm run start` 

- play a track on soundcloud
- and post here a screenshot of what appears when you play a track

**Comment by jehendeoff** [comment]
I don't know why and how, but since you commented, everything is working fine, so .... Thank you ? I don't know why it wasn't working, but now it is, so ....

**Comment by demaisj** [comment]
perfect !
