### ISSUE TITLE
Stuck at "npm run start"

### ISSUE THREAD

**Issue by xanderSP** [demaisj/soundcloud-rp#3]
Every time I write "npm run start", it gets stuck and this appears. Do you know anyway to fix?
![node bin](https://user-images.githubusercontent.com/41550725/43048969-dda01616-8db5-11e8-81e9-00a1d1f82627.PNG)

**Comment by demaisj** [comment]
Hello,

Is the message `Listenning on port 7769` showing when you start the server ?

**Comment by demaisj** [comment]
Hello,

This is normal, if the server is not displaying anything, it means that it is working properly.
To make sure it is working, you can also visit http://127.0.0.1:7769/client.js: if it shows a bunch of code, it is ok. Otherwise if your browser reports an error (like Connection Refused) there is a problem.

**Comment by xanderSP** [comment]
Ok, thank you very much!
